### ISSUE TITLE
Can't use this client side in React App

### ISSUE THREAD

**Issue by RusseII** [pqt/runescape-api#28]
I think the issue is it trying to do something with the filesystem but I didn't really look into the code.

To solve this, I just hosted the API is a nodejs lambda function and hit that from clientside.

**Comment by Joshua-F** [comment]
I don't think this would be possible even if using a different library that supported browsers. The APIs Jagex expose do not allow CORS so browsers would just block the request. You'd need to use a server as a proxy still.

**Comment by RusseII** [comment]
Makes complete sense. I think it might be useful to add somewhere in the documentation that it can only be used server-side.

**Comment by pqt** [comment]
I've gone ahead and added that to the introduction section. Great point that I somehow missed including in the v2 rewrite.

![](https://i.imgur.com/1YvDBYT.png)

I have a passion project where I'm actually doing exactly what you mentioned.

This might open the door to either update this package to consume these new endpoints, or a separate library set all together that is focused on usage within React and other frameworks if demand is there.

Repo is https://github.com/pqt/myosrs and a sample endpoint is https://myosrs.app/api/player/Paqt, it does not have CORS yet itself but it will eventually.
