### ISSUE TITLE
Adding support for RuneMetrics API

### ISSUE THREAD

**Issue by carsnwd** [pqt/runescape-api#7]
Since this wrapper was created, the [RuneMetrics API](https://runescape.wikia.com/wiki/Application_programming_interface#Runemetrics) has come out. I was gonna work on trying to add that to the wrapper when I get a chance if that sounds useful?

**Comment by Joshua-F** [comment]
While it isn't technically an official API that is meant to be used publicly, I don't personally have an issue having it added as part of this lib.
